services:
  database:
    image: mysql:latest
    restart: always
    environment:
        LANG: C.UTF-8
        LC_ALL: C.UTF-8
        MYSQL_ROOT_PASSWORD: root1234
        MYSQL_DATABASE: pencabdii
        MYSQL_USER: dbAdmin
        MYSQL_PASSWORD: root1234

    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-scripts/:/docker-entrypoint-initdb.d/
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db_data:
    driver: local