services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sebacapo123
      MYSQL_DATABASE: pencabdii
      MYSQL_USER: sebacapo
      MYSQL_PASSWORD: sebacapo123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-scripts/:/docker-entrypoint-initdb.d/
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db_data:
    driver: local