services:
 backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge