services:

 backend:

    build:

      context: .
      dockerfile: Dockerfile

    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8

    ports:
      - "3000:3000"

    restart: unless-stopped

    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge